Add label and env var for openshift release
openshift/egress-router-cni pull request #18
Opened 2020-11-10 19:00 UTC by danielmellado

This PR adds both the env var mapping egress-router-cni to CNO and also
sets the release operator flag to true.

2020-11-10 19:02 UTC, danielmellado commented
/assign @jupierce

2020-11-10 21:23 UTC, jupierce requested changes

2020-11-10 21:23 UTC, jupierce commented on Dockerfile.rhel8
> +ENV OPERATOR_NAME=cluster-network-operator
cluster-network-operator was an example. You'll want a unique name.

2020-11-10 23:23 UTC, danielmellado commented
But this is *not* an operator, is that needed even in that case?

El mar., 10 nov. 2020 22:24, Justin Pierce <notifications@github.com>
escribió:

> *@jupierce* requested changes on this pull request.
> ------------------------------
>
> In Dockerfile.rhel8
> <https://github.com/openshift/egress-router-cni/pull/18#discussion_r520882428>
> :
>
> > @@ -4,6 +4,7 @@ WORKDIR /go/src/github.com/openshift/egress-router-cni
>  ENV GO111MODULE=on
>  ENV CGO_ENABLED=1
>  ENV VERSION=rhel8 COMMIT=unset
> +ENV OPERATOR_NAME=cluster-network-operator
>
> cluster-network-operator was an example. You'll want a unique name.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/openshift/egress-router-cni/pull/18#pullrequestreview-527618454>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAKAVQ2DLKOUVXHAT34AEBLSPGVPDANCNFSM4TRBGS4A>
> .
>

2020-11-11 11:47 UTC, danielmellado commented
Yeah, after speaking with @squeed he mentioned that this seems to be only needed for operators, so I'm abandoning the change.

2020-11-11 11:47 UTC, closed without merging